// ═══════════════════════════════════════════
// STATIC DATA (CATEGORIES, DEFAULT_DB, EMOJI_MAP, etc.)
// ═══════════════════════════════════════════

const CATEGORIES = ['Protéines', 'Légumes', 'Fruits', 'Herbes & aromates', 'Épices sèches', 'Produits laitiers', 'Alternatives végétales', 'Pâtes, riz & légumes secs', 'Conserves & bocaux', 'Sauces & condiments', 'Huiles & vinaigres', 'Farines & liants', 'Graines & noix', 'Sucres & sirops', 'Bouillons & bases', 'Plats & Préparations'];

const DEFAULT_DB = [
  // PROTÉINES
  { id: 'ing_cf7b9c61', name: 'Agneau (brochettes)', emoji: '🐏', category: 'Protéines', frozen: false },
  { id: 'ing_2a9863eb', name: 'Agneau (côtelettes)', emoji: '🐏', category: 'Protéines', frozen: false },
  { id: 'ing_718d0f06', name: 'Agneau (haché)', emoji: '🐏', category: 'Protéines', frozen: false },
  { id: 'ing_75093324', name: 'Bœuf (steak)', emoji: '🐂', category: 'Protéines', frozen: false },
  { id: 'ing_dfc3861f', name: 'Bœuf (steaks hachés)', emoji: '🐂', category: 'Protéines', frozen: false },
  { id: 'p2', name: 'Bœuf (haché)', emoji: '🐂', category: 'Protéines', frozen: false },
  { id: 'p6', name: 'Crevettes', emoji: '🦐', category: 'Protéines', frozen: false },
  { id: 'p8', name: 'Dinde', emoji: '🦃', category: 'Protéines', frozen: false },
  { id: 'ing_3af61cd7', name: 'Jambon (cru)', emoji: '🍖', category: 'Protéines', frozen: false },
  { id: 'ing_e54e90d6', name: 'Jambon (cuit)', emoji: '🍖', category: 'Protéines', frozen: false },
  { id: 'ing_4318228f', name: 'Porc (côtes)', emoji: '🐖', category: 'Protéines', frozen: false },
  { id: 'ing_ff989a00', name: 'Porc (saucisses)', emoji: '🐖', category: 'Protéines', frozen: false },
  { id: 'ing_6a03cb36', name: 'Porc (haché)', emoji: '🐖', category: 'Protéines', frozen: false },
  { id: 'p1', name: 'Poulet', emoji: '🐔', category: 'Protéines', frozen: false },
  { id: 'ing_1d1a4d91', name: 'Poulet (brochettes)', emoji: '🍗', category: 'Protéines', frozen: false },
  { id: 'ing_108aae85', name: 'Poulet (filets)', emoji: '🍗', category: 'Protéines', frozen: false },
  { id: 'p3', name: 'Saumon', emoji: '🐟', category: 'Protéines', frozen: false },
  { id: 'ing_8f3ecde3', name: 'Saumon (fumé)', emoji: '🐟', category: 'Protéines', frozen: false },
  { id: 'p12', name: 'Thon (frais)', emoji: '🐟', category: 'Protéines', frozen: false },
  { id: 'p7', name: 'Tofu', emoji: '🍱', category: 'Protéines', frozen: false },
  { id: 'p4', name: 'Oeuf', emoji: '🥚', category: 'Protéines', frozen: false },
  // LÉGUMES
  { id: 'ing_3d5ebfb0', name: 'Asperges (blanches)', emoji: '🥦', category: 'Légumes', frozen: false },
  { id: 'ing_80919c4c', name: 'Asperges (vertes)', emoji: '🥦', category: 'Légumes', frozen: false },
  { id: 'l10', name: 'Aubergine', emoji: '🍆', category: 'Légumes', frozen: false },
  { id: 'l18', name: 'Betterave', emoji: '🫐', category: 'Légumes', frozen: false },
  { id: 'l7', name: 'Brocoli', emoji: '🥦', category: 'Légumes', frozen: false },
  { id: 'ing_d12588ef', name: 'Butternut', emoji: '🎃', category: 'Légumes', frozen: false },
  { id: 'l4', name: 'Carottes', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'l17', name: 'Céleri', emoji: '🌿', category: 'Légumes', frozen: false },
  { id: 'l9', name: 'Champignons', emoji: '🍄', category: 'Légumes', frozen: false },
  { id: 'ing_af109abe', name: 'Chou (blanc)', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'ing_1103ea00', name: 'Chou (rouge)', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'ing_20d74fa1', name: 'Chou (vert)', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'ing_b0bbfa45', name: 'Chou (de Bruxelles)', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'l14', name: 'Concombre', emoji: '🥒', category: 'Légumes', frozen: false },
  { id: 'l5', name: 'Courgettes', emoji: '🥒', category: 'Légumes', frozen: false },
  { id: 'l8', name: 'Épinards', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'l25', name: 'Épinards (surgelés)', emoji: '🥬', category: 'Légumes', frozen: true },
  { id: 'l19', name: 'Fenouil', emoji: '🌿', category: 'Légumes', frozen: false },
  { id: 'ing_655cf854', name: 'Haricots verts', emoji: '🫘', category: 'Légumes', frozen: false },
  { id: 'ing_218e4ae6', name: 'Maïs', emoji: '🌽', category: 'Légumes', frozen: false },
  { id: 'ing_7993a4a8', name: 'Navets', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'custom_1774564440142', name: 'Oignon', emoji: '🧅', category: 'Légumes', frozen: false },
  { id: 'l23', name: 'Patate douce', emoji: '🍠', category: 'Légumes', frozen: false },
  { id: 'l12', name: 'Poireaux', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'l6', name: 'Poivrons', emoji: '🫑', category: 'Légumes', frozen: false },
  { id: 'l11', name: 'Pommes de terre', emoji: '🥔', category: 'Légumes', frozen: false },
  { id: 'ing_5965f0d1', name: 'Radis', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'ing_2b32a325', name: 'Rutabaga', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'l15', name: 'Salade (verte)', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 're_ing_17745578567367', name: 'Tomate', emoji: '🍅', category: 'Légumes', frozen: false },
  { id: 're_ing_177460232780610', name: 'Laitue (cœur)', emoji: '🥬', category: 'Légumes', frozen: false },
  // FRUITS
  { id: 'fr8', name: 'Ananas', emoji: '🍍', category: 'Fruits', frozen: false },
  { id: 'l13', name: 'Avocat', emoji: '🥑', category: 'Fruits', frozen: false },
  { id: 're_ing_17745594032561', name: 'Banane', emoji: '🍌', category: 'Fruits', frozen: false },
  { id: 'fr3', name: 'Citron (vert)', emoji: '🍋‍🟩', category: 'Fruits', frozen: false },
  { id: 'fr7', name: 'Fraises', emoji: '🍓', category: 'Fruits', frozen: false },
  { id: 'fr9', name: 'Framboises', emoji: '🍓', category: 'Fruits', frozen: false },
  { id: 'ing_4d0542c2', name: 'Kiwi', emoji: '🥝', category: 'Fruits', frozen: false },
  { id: 'fr6', name: 'Mangue', emoji: '🥭', category: 'Fruits', frozen: false },
  { id: 'ing_cfbc312b', name: 'Myrtilles', emoji: '🫐', category: 'Fruits', frozen: false },
  { id: 'fr2', name: 'Orange', emoji: '🍊', category: 'Fruits', frozen: false },
  { id: 'ing_397904fc', name: 'Poire', emoji: '🍐', category: 'Fruits', frozen: false },
  { id: 'fr4', name: 'Pomme', emoji: '🍎', category: 'Fruits', frozen: false },
  { id: 'ing_b1cb1675', name: 'Raisin', emoji: '🍇', category: 'Fruits', frozen: false },
  // HERBES & AROMATES
  { id: 'l3', name: 'Ail', emoji: '🧄', category: 'Herbes & aromates', frozen: false },
  { id: 'ing_f145ad5b', name: 'Aneth frais', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h1', name: 'Basilic', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h3', name: 'Ciboulette', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'ing_629161a0', name: 'Citronnelle', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h6', name: 'Coriandre', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'l21', name: 'Échalotes', emoji: '🧅', category: 'Herbes & aromates', frozen: false },
  { id: 'h10', name: 'Estragon frais', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'custom_1774558297874', name: 'Herbes (de Provence)', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h9', name: 'Laurier', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h7', name: 'Menthe', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h2', name: 'Persil plat haché', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h5', name: 'Romarin', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h11', name: 'Sauge', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'h4', name: 'Thym', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  // ÉPICES SÈCHES
  { id: 'ing_f9046c65', name: 'Ail (en poudre)', emoji: '🧄', category: 'Épices sèches', frozen: false },
  { id: 'ing_c9619be9', name: 'Baies de genièvre', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'ing_703e33b5', name: 'Bouquet garni', emoji: '🍃', category: 'Épices sèches', frozen: false },
  { id: 'e5', name: 'Cannelle', emoji: '🪵', category: 'Épices sèches', frozen: false },
  { id: 'ing_74211603', name: 'Cardamome', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'ing_194da956', name: 'Clous de girofle', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e13', name: 'Coriandre (moulue)', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e1', name: 'Cumin', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e3', name: 'Curcuma', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e4', name: 'Curry', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'ing_835261eb', name: 'Épices couscous', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'ing_2ab458c2', name: 'Épices tajine', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e8', name: 'Gingembre (moulu)', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e12', name: 'Noix de muscade', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'ing_8ebced87', name: 'Oignon (en poudre)', emoji: '🧂', category: 'Épices sèches', frozen: false },
  { id: 'e2', name: 'Paprika', emoji: '🌶️', category: 'Épices sèches', frozen: false },
  { id: 'e6', name: 'Piment', emoji: '🌶️', category: 'Épices sèches', frozen: false },
  { id: 'ing_39626e2e', name: 'Piment (espelette)', emoji: '🌶️', category: 'Épices sèches', frozen: false },
  { id: 'e7', name: 'Poivre noir', emoji: '🧂', category: 'Épices sèches', frozen: false },
  { id: 'e9', name: 'Ras el hanout', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'e11', name: 'Sel', emoji: '🧂', category: 'Épices sèches', frozen: false },
  { id: 'ing_9f898328', name: 'Sumac', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'ing_076865df', name: 'Zaatar', emoji: '🫙', category: 'Épices sèches', frozen: false },
  // PRODUITS LAITIERS
  { id: 'la1', name: 'Beurre', emoji: '🧈', category: 'Produits laitiers', frozen: false },
  { id: 'la3', name: 'Crème (fraîche)', emoji: '🥛', category: 'Produits laitiers', frozen: false },
  { id: 'la11', name: 'Feta', emoji: '🧀', category: 'Produits laitiers', frozen: false },
  { id: 'ing_923ba85e', name: 'Fromage (blanc)', emoji: '🥛', category: 'Produits laitiers', frozen: false },
  { id: 'la6', name: 'Fromage (chèvre)', emoji: '🧀', category: 'Produits laitiers', frozen: false },
  { id: 'ing_117072a3', name: 'Ghee', emoji: '🧈', category: 'Produits laitiers', frozen: false },
  { id: 'la7', name: 'Gruyère', emoji: '🧀', category: 'Produits laitiers', frozen: false },
  { id: 'la2', name: 'Lait', emoji: '🥛', category: 'Produits laitiers', frozen: false },
  { id: 'la5', name: 'Mozzarella', emoji: '🧀', category: 'Produits laitiers', frozen: false },
  { id: 'la4', name: 'Parmesan râpé', emoji: '🧀', category: 'Produits laitiers', frozen: false },
  { id: 'la12', name: 'Ricotta', emoji: '🧀', category: 'Produits laitiers', frozen: false },
  { id: 'la8', name: 'Yaourt (nature)', emoji: '🥛', category: 'Produits laitiers', frozen: false },
  // ALTERNATIVES VÉGÉTALES
  { id: 'ing_6869b309', name: 'Crème (amande)', emoji: '🥛', category: 'Alternatives végétales', frozen: false },
  { id: 'ing_819e078e', name: 'Crème (cajou)', emoji: '🥛', category: 'Alternatives végétales', frozen: false },
  { id: 'la10', name: 'Crème (soja)', emoji: '🥛', category: 'Alternatives végétales', frozen: false },
  { id: 'ing_8a8a6ea4', name: 'Lait (amande)', emoji: '🌰', category: 'Alternatives végétales', frozen: false },
  { id: 'la9', name: 'Lait (coco)', emoji: '🥥', category: 'Alternatives végétales', frozen: false },
  { id: 'ing_5e5e98ef', name: 'Yaourt (coco)', emoji: '🥥', category: 'Alternatives végétales', frozen: false },
  { id: 'ing_6e72af45', name: 'Beurre (amande)', emoji: '🧈', category: 'Alternatives végétales', frozen: false },
  { id: 'ing_4912c948', name: 'Beurre (cacahuète)', emoji: '🧈', category: 'Alternatives végétales', frozen: false },
  { id: 'ing_7ed44517', name: 'Beurre (cajou)', emoji: '🧈', category: 'Alternatives végétales', frozen: false },
  // PÂTES, RIZ & LÉGUMES SECS
  { id: 'pa10', name: 'Boulgour', emoji: '🌾', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa9', name: 'Couscous', emoji: '🌾', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'ing_91cb1675', name: 'Haricot (noir)', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa7', name: 'Haricot (rouge)', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'ing_3b1cb167', name: 'Haricot (sec)', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'ing_f1cb1675', name: 'Lentilles (corail)', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa5', name: 'Lentilles (rouges)', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa4', name: 'Lentilles (vertes)', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'ing_81cb1675', name: 'Pâtes', emoji: '🍝', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa2', name: 'Penne', emoji: '🍝', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa6', name: 'Pois chiches', emoji: '🫘', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa8', name: 'Quinoa', emoji: '🌾', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'ing_92cb1675', name: 'Riz', emoji: '🍚', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa3', name: 'Riz (basmati)', emoji: '🍚', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa12', name: 'Riz (complet)', emoji: '🍚', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa1', name: 'Spaghetti', emoji: '🍝', category: 'Pâtes, riz & légumes secs', frozen: false },
  { id: 'pa11', name: 'Tagliatelles', emoji: '🍝', category: 'Pâtes, riz & légumes secs', frozen: false },
  // CONSERVES & BOCAUX
  { id: 'c9', name: 'Anchois', emoji: '🐟', category: 'Conserves & bocaux', frozen: false },
  { id: 'ing_d9e889bc', name: 'Betterave (fermentée)', emoji: '🥫', category: 'Conserves & bocaux', frozen: false },
  { id: 'ing_6831eca7', name: 'Choucroute', emoji: '🥫', category: 'Conserves & bocaux', frozen: false },
  { id: 're_ing_17745578567330', name: 'Haricot (rouge)', emoji: '🫘', category: 'Conserves & bocaux', frozen: false },
  { id: 'c11', name: 'Haricot (blanc)', emoji: '🫘', category: 'Conserves & bocaux', frozen: false },
  { id: 're_ing_17745578567341', name: 'Tomate (jus)', emoji: '🍅', category: 'Conserves & bocaux', frozen: false },
  { id: 'c6', name: 'Maïs (boîte)', emoji: '🌽', category: 'Conserves & bocaux', frozen: false },
  { id: 'ing_9a502014', name: 'Oignon (rouge vinaigré)', emoji: '🫙', category: 'Conserves & bocaux', frozen: false },
  { id: 'c2', name: 'Olive (noire)', emoji: '🫒', category: 'Conserves & bocaux', frozen: false },
  { id: 'c3', name: 'Olive (verte)', emoji: '🫒', category: 'Conserves & bocaux', frozen: false },
  { id: 'c10', name: 'Pois chiches (boîte)', emoji: '🫘', category: 'Conserves & bocaux', frozen: false },
  { id: 'c8', name: 'Sardines (boîte)', emoji: '🐟', category: 'Conserves & bocaux', frozen: false },
  { id: 'c7', name: 'Thon (boîte)', emoji: '🐟', category: 'Conserves & bocaux', frozen: false },
  { id: 'c1', name: 'Tomate (concassée)', emoji: '🫙', category: 'Conserves & bocaux', frozen: false },
  { id: 'ing_9b869e28', name: 'Tomate (pelée)', emoji: '🍅', category: 'Conserves & bocaux', frozen: false },
  // SAUCES & CONDIMENTS
  { id: 'ing_3dc90a50', name: 'Baies roses (vinaigre)', emoji: '🍶', category: 'Sauces & condiments', frozen: false },
  { id: 'ing_db9f2c67', name: 'Câpres', emoji: '🌱', category: 'Sauces & condiments', frozen: false },
  { id: 'ing_89e53d1f', name: 'Tomate (concentré)', emoji: '🍅', category: 'Sauces & condiments', frozen: false },
  { id: 'ing_79899606', name: 'Cornichons', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 're_ing_17745648782944', name: 'Vanille (extrait)', emoji: '🧪', category: 'Sauces & condiments', frozen: false },
  { id: 'ing_1daa2480', name: 'Gomasio', emoji: '🥣', category: 'Sauces & condiments', frozen: false },
  { id: 'e10', name: 'Harissa', emoji: '🌶️', category: 'Sauces & condiments', frozen: false },
  { id: 's3', name: 'Ketchup', emoji: '🔴', category: 'Sauces & condiments', frozen: false },
  { id: 'ing_ff547278', name: 'Sauce (teriyaki marinade)', emoji: '🥣', category: 'Sauces & condiments', frozen: false },
  { id: 's4', name: 'Mayonnaise', emoji: '😋', category: 'Sauces & condiments', frozen: false },
  { id: 's2', name: 'Moutarde', emoji: '🟡', category: 'Sauces & condiments', frozen: false },
  { id: 's10', name: 'Pesto', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 's1', name: 'Sauce soja', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 'ing_23452b20', name: 'Sauce soja (sucrée)', emoji: '🍣', category: 'Sauces & condiments', frozen: false },
  { id: 's9', name: 'Sauce teriyaki', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 's5', name: 'Sauce tomate', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 's7', name: 'Sauce worcestershire', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 's8', name: 'Tabasco', emoji: '🌶️', category: 'Sauces & condiments', frozen: false },
  { id: 's11', name: 'Tahini', emoji: '🫙', category: 'Sauces & condiments', frozen: false },
  { id: 're_ing_177455318777112', name: 'Vin blanc (sec)', emoji: '🥂', category: 'Sauces & condiments', frozen: false },
  { id: 're_ing_177460232780712', name: 'Vinaigrette', emoji: '🥣', category: 'Sauces & condiments', frozen: false },
  // HUILES & VINAIGRES
  { id: 'ing_902a468c', name: 'Vinaigre (crème balsamique)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_412ab269', name: 'Huile (avocat)', emoji: '🥑', category: 'Huiles & vinaigres', frozen: false },
  { id: 'hu1', name: 'Huile (olive)', emoji: '🫒', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_5a99fbd8', name: 'Huile (coco)', emoji: '🥥', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_bbd34abf', name: 'Huile (lin)', emoji: '🌾', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_3db09014', name: 'Huile (macadamia)', emoji: '🌰', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_4fbead2c', name: 'Huile (pépins de raisin)', emoji: '🍇', category: 'Huiles & vinaigres', frozen: false },
  { id: 'hu3', name: 'Huile (sésame)', emoji: '🫙', category: 'Huiles & vinaigres', frozen: false },
  { id: 'hu2', name: 'Huile (tournesol)', emoji: '🫙', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_3030d1dd', name: 'Vinaigre (miel)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'hu4', name: 'Vinaigre (balsamique)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_231780da', name: 'Vinaigre (blanc)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'hu5', name: 'Vinaigre (cidre)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_24a55de1', name: 'Vinaigre (riz brun)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'hu6', name: 'Vinaigre (vin)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  { id: 'ing_14bac981', name: 'Vinaigre (vin blanc)', emoji: '🍶', category: 'Huiles & vinaigres', frozen: false },
  // FARINES & LIANTS
  { id: 'ing_8542f7e8', name: 'Bicarbonate de soude', emoji: '🥣', category: 'Farines & liants', frozen: false },
  { id: 'ing_2b79be3f', name: 'Cacao (poudre)', emoji: '🍫', category: 'Farines & liants', frozen: false },
  { id: 'fa4', name: 'Chapelure', emoji: '🍞', category: 'Farines & liants', frozen: false },
  { id: 'ing_92833d82', name: 'Farine (amande)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_dfcd6aab', name: 'Farine (épeautre)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'fa1', name: 'Farine (blé)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_66096961', name: 'Farine (châtaigne)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_0928b3c7', name: 'Farine (coco)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_7b77a2ee', name: 'Farine (lin)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_5f35fe3a', name: 'Farine (macadamia)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_96254543', name: 'Farine (manioc)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_0a8a6ea4', name: 'Farine (patate douce)', emoji: '🍠', category: 'Farines & liants', frozen: false },
  { id: 'ing_0b10a694', name: 'Farine (pois chiche)', emoji: '🫘', category: 'Farines & liants', frozen: false },
  { id: 'fa3', name: 'Farine (riz)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_eccf1dc9', name: 'Farine (sarrasin)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'fa2', name: 'Fécule (maïs)', emoji: '🌾', category: 'Farines & liants', frozen: false },
  { id: 'ing_5ba398f9', name: 'Fécule (tapioca)', emoji: '🌽', category: 'Farines & liants', frozen: false },
  { id: 'fa5', name: 'Levure (chimique)', emoji: '🫙', category: 'Farines & liants', frozen: false },
  { id: 'ing_b78c4724', name: 'Psyllium', emoji: '🌾', category: 'Farines & liants', frozen: false },
  // GRAINES & NOIX
  { id: 'g1', name: 'Amandes', emoji: '🌰', category: 'Graines & noix', frozen: false },
  { id: 'ing_0f0fd34b', name: 'Amlou', emoji: '🥜', category: 'Graines & noix', frozen: false },
  { id: 'ing_0c459198', name: 'Cacahuètes', emoji: '🥜', category: 'Graines & noix', frozen: false },
  { id: 'ing_17f021c3', name: 'Graines (chia)', emoji: '🌻', category: 'Graines & noix', frozen: false },
  { id: 'ing_91189a98', name: 'Graines (courge)', emoji: '🌻', category: 'Graines & noix', frozen: false },
  { id: 'ing_d6077c14', name: 'Graines (lin)', emoji: '🌻', category: 'Graines & noix', frozen: false },
  { id: 'g4', name: 'Graines de sésame', emoji: '🌻', category: 'Graines & noix', frozen: false },
  { id: 'g5', name: 'Graines (tournesol)', emoji: '🌻', category: 'Graines & noix', frozen: false },
  { id: 'ing_8551e5b3', name: 'Noix (mélange)', emoji: '🌰', category: 'Graines & noix', frozen: false },
  { id: 'g7', name: 'Noisettes', emoji: '🌰', category: 'Graines & noix', frozen: false },
  { id: 'g2', name: 'Noix', emoji: '🌰', category: 'Graines & noix', frozen: false },
  { id: 'g3', name: 'Noix (cajou)', emoji: '🌰', category: 'Graines & noix', frozen: false },
  { id: 'ing_260cb1b2', name: 'Noix de coco (râpée)', emoji: '🥥', category: 'Graines & noix', frozen: false },
  { id: 'g8', name: 'Noix (pécan)', emoji: '🌰', category: 'Graines & noix', frozen: false },
  { id: 'g6', name: 'Pignons de pin', emoji: '🌲', category: 'Graines & noix', frozen: false },
  { id: 'ing_8f8ec219', name: 'Pistaches', emoji: '🌰', category: 'Graines & noix', frozen: false },
  // SUCRES & SIROPS
  { id: 'su6', name: 'Cassonade', emoji: '🍬', category: 'Sucres & sirops', frozen: false },
  { id: 'ing_4aaa26f2', name: 'Confiture', emoji: '🍯', category: 'Sucres & sirops', frozen: false },
  { id: 'ing_8c4f0882', name: 'Miel', emoji: '🍯', category: 'Sucres & sirops', frozen: false },
  { id: 'su5', name: 'Sirop (agave)', emoji: '🍯', category: 'Sucres & sirops', frozen: false },
  { id: 'su3', name: 'Sirop (érable)', emoji: '🍁', category: 'Sucres & sirops', frozen: false },
  { id: 'ing_4e5e98ef', name: 'Sirop (dattes)', emoji: '🍯', category: 'Sucres & sirops', frozen: false },
  { id: 'ing_c8d71c86', name: 'Sirop (Liège)', emoji: '🍯', category: 'Sucres & sirops', frozen: false },
  { id: 'su1', name: 'Sucre (blanc)', emoji: '🍬', category: 'Sucres & sirops', frozen: false },
  { id: 'su4', name: 'Sucre (glace)', emoji: '🍬', category: 'Sucres & sirops', frozen: false },
  { id: 'su2', name: 'Sucre (roux)', emoji: '🍬', category: 'Sucres & sirops', frozen: false },
  // BOUILLONS & BASES
  { id: 'b3', name: 'Bouillon (bœuf)', emoji: '🍲', category: 'Bouillons & bases', frozen: false },
  { id: 'b2', name: 'Bouillon (légumes)', emoji: '🍲', category: 'Bouillons & bases', frozen: false },
  { id: 'b1', name: 'Bouillon (poulet)', emoji: '🍲', category: 'Bouillons & bases', frozen: false },
  // PROTÉINES
  { id: 'custom_1774612858955', name: 'Lard/Lardons', emoji: '🥓', category: 'Protéines', frozen: false },
  { id: 'custom_1774612904876', name: 'Saucisse (Merguez)', emoji: '🌭', category: 'Protéines', frozen: false },
  { id: 'custom_1774612922834', name: 'Saucisse (Chipolata)', emoji: '🌭', category: 'Protéines', frozen: false },
  { id: 'custom_1774612969916', name: 'Cabillaud (frais)', emoji: '🐟', category: 'Protéines', frozen: false },
  // LÉGUMES
  { id: 'custom_1774613100261', name: 'Petits Pois', emoji: '🫛', category: 'Légumes', frozen: true },
  // FRUITS
  { id: 'custom_1774613155264', name: 'Citron (jaune)', emoji: '🍋', category: 'Fruits', frozen: false },
  // HERBES & AROMATES
  { id: 'custom_1774613375673', name: 'Origan', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  { id: 'custom_1774613394857', name: 'Gingembre', emoji: '🫚', category: 'Herbes & aromates', frozen: false },
  // LÉGUMES
  { id: 'custom_1774621829405', name: 'Chicon (Endive)', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'custom_1774621846615', name: 'Panais', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'custom_1774621871983', name: 'Topinambour', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'custom_1774621899460', name: 'Radis noir', emoji: '🥕', category: 'Légumes', frozen: false },
  { id: 'custom_1774621927475', name: 'Blette', emoji: '🥬', category: 'Légumes', frozen: false },
  { id: 'custom_1774621971174', name: 'Artichaut', emoji: '💚', category: 'Légumes', frozen: false },
  { id: 'custom_1774622081386', name: 'Choux-Rave', emoji: '🥦', category: 'Légumes', frozen: false },
  { id: 'custom_1774622100501', name: 'Chou-Fleur', emoji: '🥦', category: 'Légumes', frozen: false },
  { id: 'custom_1774622186442', name: 'Potimaron', emoji: '🎃', category: 'Légumes', frozen: false },
  // FRUITS
  { id: 'custom_1774622309649', name: 'Rhubarbe', emoji: '🌱', category: 'Fruits', frozen: false },
  { id: 'custom_1774622347567', name: 'Abricot', emoji: '🍑', category: 'Fruits', frozen: false },
  { id: 'custom_1774622362103', name: 'Cerise', emoji: '🍒', category: 'Fruits', frozen: false },
  // LÉGUMES
  { id: 'custom_1774622397021', name: 'Tomate-Cerise', emoji: '🍅', category: 'Légumes', frozen: false },
  // FRUITS
  { id: 'custom_1774622427609', name: 'Figue', emoji: '🫐', category: 'Fruits', frozen: false },
  { id: 'custom_1774622477982', name: 'Dattes', emoji: '🌴', category: 'Fruits', frozen: false },
  // HERBES & AROMATES
  { id: 'custom_1774622673047', name: 'Cerfeuil', emoji: '🌿', category: 'Herbes & aromates', frozen: false },
  // ÉPICES SÈCHES
  { id: 'custom_1774622816282', name: 'Anis étoilé (Badiane)', emoji: '🫙', category: 'Épices sèches', frozen: false },
  { id: 'custom_1774622844203', name: 'Poivre blanc', emoji: '🧂', category: 'Épices sèches', frozen: false },
  { id: 'custom_1774622868785', name: 'Safran', emoji: '🏵️', category: 'Épices sèches', frozen: false },
  // CONSERVES & BOCAUX
  { id: 'custom_1774623046866', name: 'Haricot (Germes)', emoji: '🫘', category: 'Conserves & bocaux', frozen: false },
  // BOUILLONS & BASES
  { id: 'custom_1774623283084', name: 'Miso (Stock)', emoji: '🫙', category: 'Bouillons & bases', frozen: false },
  // FARINES & LIANTS
  { id: 'custom_1774623908308', name: 'Pâte (Brisée)', emoji: '🧑‍🍳', category: 'Farines & liants', frozen: false },
  { id: 'custom_1774624046919', name: 'Pâte (Feuilletée)', emoji: '🧑‍🍳', category: 'Farines & liants', frozen: false },
  // SUCRES & SIROPS
  { id: 'custom_1774624206876', name: 'Sucre Vanillé', emoji: '🍬', category: 'Sucres & sirops', frozen: false },
  // PLATS & PRÉPARATIONS
  { id: 'ing_croquettes', name: 'Croquettes', emoji: '🥔', category: 'Plats & Préparations', frozen: true },
  { id: 'ing_frites', name: 'Frites', emoji: '🍟', category: 'Plats & Préparations', frozen: true },
  { id: 'ing_puree_pdterre', name: 'Purée de pomme de terre', emoji: '🥔', category: 'Plats & Préparations', frozen: false },
];


const EMOJI_MAP = {
  // PROTÉINES & VIANDES
  'poulet': ['🍗', '🐔'], 'bœuf': ['🥩', '🐂'], 'saumon': ['🐟', '🍣'], 'thon': ['🐟'], 'poisson': ['🐟', '🎣', '🍣'],
  'œuf': ['🥚', '🍳'], 'oeuf': ['🥚', '🍳'], 'porc': ['🥩', '🥓', '🐖'], 'agneau': ['🥩', '🐏', '🐑'], 'dinde': ['🍗', '🦃'],
  'crevett': ['🦐'], 'gambas': ['🦐'], 'tofu': ['🫙', '🍱'], 'merguez': ['🌭', '🌶️'], 'sardine': ['🐟', '🥫'],
  'jambon': ['🥓', '🍖'], 'lardons': ['🥓'], 'bacon': ['🥓'], 'canard': ['🍗', '🦆'], 'lapin': ['🥩', '🐇'],
  'steak': ['🥩'], 'colloque': ['🐚'], 'moule': ['🐚'], 'huître': ['🐚'], 'calamar': ['🦑'], 'poulpe': ['🐙'],

  // LÉGUMES & TUBERCULES
  'tomate': ['🍅'], 'oignon': ['🧅'], 'ail': ['🧄'], 'carotte': ['🥕'], 'courgett': ['🥒'], 'concombre': ['🥒'],
  'poivron': ['🫑', '🌶️'], 'brocoli': ['🥦'], 'épinard': ['🥬'], 'champignon': ['🍄'], 'aubergine': ['🍆'],
  'pomme de terre': ['🥔'], 'patate': ['🥔', '🍠'], 'poireau': ['🥬'], 'avocat': ['🥑'], 'salade': ['🥬', '🥗'],
  'chou': ['🥬', '🥦'], 'céleri': ['🌿'], 'betterave': ['🍠', '🥗'], 'fenouil': ['🌿'], 'asperge': ['🌿'],
  'gingembre': ['🫚', '🌿'], 'édamame': ['🫘'], 'petit pois': ['🫛', '🫘'], 'radis': ['🌿'], 'artichaut': ['🥦'],
  'frites': ['🍟'], 'croquettes': ['🥔', '🍘'], 'purée': ['🥔', '🥣'],

  // FRUITS
  'citron': ['🍋'], 'orange': ['🍊'], 'pomme': ['🍎', '🍏'], 'banane': ['🍌'], 'mangue': ['🥭'], 'fraise': ['🍓'],
  'framboise': ['🍓', '🍇'], 'ananas': ['🍍'], 'poire': ['🍐'], 'pêche': ['🍑'], 'cerise': ['🍒'], 'melon': ['🍈'],
  'pastèque': ['🍉'], 'kiwi': ['🥝'], 'myrtille': ['🫐'], 'mûre': ['🫐'], 'abricot': ['🍑'], 'figue': ['🫐'],

  // HERBES & AROMATES
  'basilic': ['🌿'], 'persil': ['🌿'], 'thym': ['🌿'], 'romarin': ['🌿'], 'coriandre': ['🌿'],
  'menthe': ['🌿', '🍃'], 'origan': ['🌿'], 'laurier': ['🌿'], 'sauge': ['🌿'], 'estragon': ['🌿'],
  'ciboulette': ['🌿'], 'aneth': ['🌿'], 'curcuma': ['🫙', '🟡'],

  // ÉPICES & CONDIMENTS
  'cumin': ['🫙'], 'paprika': ['🫙', '🌶️'], 'curry': ['🫙', '🍛'], 'cannelle': ['🫙', '🪵'],
  'piment': ['🌶️'], 'poivre': ['🫙', '⚫'], 'sel': ['🧂'], 'muscade': ['🫙', '🌰'], 'harissa': ['🌶️'],
  'poudre': ['🧂', '🫙'], 'moutarde': ['🫙', '🟡'], 'ketchup': ['🫙', '🍅'], 'mayo': ['🫙', '🥚'], 'pesto': ['🫙', '🌿'], 
  'tahini': ['🫙'], 'teriyaki': ['🫙'], 'soja': ['🫙', '🥛'], 'vinaigre': ['🫙'], 'huître': ['🥫'],
  'conserve': ['🥫'], 'boîte': ['🥫', '📦'], 'bocal': ['🫙'],

  // LAITIERS & FROMAGES
  'beurre': ['🧈'], 'lait': ['🥛'], 'crème': ['🥛'], 'yaourt': ['🥛', '🥣'], 'coco': ['🥥', '🥛'],
  'fromage': ['🧀'], 'parmesan': ['🧀'], 'mozzarella': ['🧀'], 'chèvre': ['🧀'], 'gruyère': ['🧀'],
  'feta': ['🧀'], 'ricotta': ['🧀'], 'mascarpone': ['🥛'], 'emmental': ['🧀'], 'comté': ['🧀'],

  // FÉCULENTS & CÉRÉALES
  'spaghetti': ['🍝'], 'penne': ['🍝'], 'pâtes': ['🍝'], 'riz': ['🍚'], 'nouilles': ['🍜'],
  'lentille': ['🫘'], 'pois': ['🫘'], 'quinoa': ['🌾'], 'couscous': ['🌾'], 'boulgour': ['🌾'],
  'haricot': ['🫘'], 'maïs': ['🌽'], 'farine': ['🌾'], 'fécule': ['🌾'], 'levure': ['🫙'],
  'pain': ['🍞', '🥖'], 'baguette': ['🥖'], 'burger': ['🍔'], 'pizza': ['🍕'], 'galette': ['🥞'],

  // HUILES & LIQUIDES
  'huile': ['🫒', '🫙'], 'vinaigre': ['🫙'], 'eau': ['💧', '🥤'], 'vin': ['🍷'], 'bière': ['🍺'],
  'jus': ['🧃'], 'cidre': ['🍺'],

  // GRAINES & NOIX
  'amande': ['🌰'], 'noix': ['🌰'], 'cajou': ['🌰'], 'sésame': ['🫙'], 'tournesol': ['🌻'],
  'pignon': ['🌲', '🌰'], 'noisette': ['🌰'], 'pécan': ['🌰'], 'cacahuète': ['🥜'],

  // SUCRÉ & AUTRES
  'sucre': ['🍬', '🍭'], 'sirop': ['🍁', '🍯'], 'miel': ['🍯'], 'cassonade': ['🍬'],
  'chocolat': ['🍫'], 'café': ['☕'], 'thé': ['🍵'], 'confiture': ['🍯'], 'glace': ['🍦'],
  'bouillon': ['🍲'], 'fond': ['🍲'], 'miso': ['🫙'], 'algue': ['🌿', '🍣'],
};


const EMOJI_CATEGORY_DEFAULTS = {
  'Protéines': '🥩', 'Légumes': '🥦', 'Fruits': '🍎', 'Herbes & aromates': '🌿',
  'Épices sèches': '🫙', 'Produits laitiers': '🧀', 'Alternatives végétales': '🥛',
  'Pâtes, riz & légumes secs': '🍝', 'Conserves & bocaux': '🥫', 'Sauces & condiments': '🫙',
  'Huiles & vinaigres': '🫒', 'Farines & liants': '🌾', 'Graines & noix': '🌰',
  'Sucres & sirops': '🍬', 'Bouillons & bases': '🍲', 'Plats & Préparations': '🍱'
};

const FILTER_LABELS = [
  { id: 'all', label: '🍱 Tous' },
  { id: 'selected', label: '✅ Sélectionnés', cls: 'stock' },
  { id: 'cart', label: '🛒 Liste courses', cls: 'terra' },
  { id: 'pinned', label: '📌 Épinglés' },
  { id: 'frozen', label: '❄️ Surgelés' },
  ...CATEGORIES.map(c => ({ id: c, label: (EMOJI_CATEGORY_DEFAULTS[c] ? EMOJI_CATEGORY_DEFAULTS[c] + ' ' : '') + c }))
];
